from gym.envs.registration import register

register(
    id='MECenv-v0',
    entry_point='utils.env_0:MECenv',
    max_episode_steps=60,
)
register(
    id='MECenv-v1',
    entry_point='utils.env_1:MECenv',
    max_episode_steps=60,
)
register(
    id='MECenv-v2',
    entry_point='utils.env_2:MECenv',
    max_episode_steps=60,
)
register(
    id='MECenv-v3',
    entry_point='utils.env_3:MECenv',
    max_episode_steps=60,
)
register(
    id='MECenv-v4',
    entry_point='utils.env_4:MECenv',
    max_episode_steps=60,
)
register(
    id='MECenv-v5',
    entry_point='utils.env_5:MECenv',
    max_episode_steps=60,
)
register(
    id='MECenv-v6',
    entry_point='utils.env_6:MECenv',
    max_episode_steps=60,
)
register(
    id='MECenv-v7',
    entry_point='utils.env_7:MECenv',
    max_episode_steps=60,
)
register(
    id='MECenv-v8',
    entry_point='utils.env_8:MECenv',
    max_episode_steps=60,
)
register(
    id='MECenv-v9',
    entry_point='utils.env_9:MECenv',
    max_episode_steps=60,
)
register(
    id='MECenv-v10',
    entry_point='utils.env_10:MECenv',
    max_episode_steps=60,
)