import numpy as np
import random
import math
class Base:
    def __init__(self):
        self.task_max_delay = 6
        self.max_link_num = 6
        self.MEC_coverage_range = 500
        self.UAV_coverage_range = 150
        self.uav_queue_length = 30
        self.mec_queue_length = 30
        self.uav_cpu_freq = 180 * (10 ** 9)
        self.mec_cpu_freq = 360 * (10 ** 9)
        self.default_increase_price = 9 * (10 ** -10)
        self.max_unit_pricing = 20 * (10 ** -9)
        self.MEC_unit_price = 100 * (10 ** -10)
        self.UAV_unit_price = 100 * (10 ** -10)
        self.mec_bandwidth = 20 * 10 ** 6
        self.uav_bandwidth = 10 * 10 ** 6
        self.field_X = [0, 1000]
        self.field_Y = [0, 1000]
        self.max_run_time = 30
        self.run_slot = 0.5
        self.max_run_slot = 60
        self.marker_indice = 10
        self.task_update_slot = 0.1
        self.mobility_slot = 1
        self.max_mobility_slot = 30
        self.UAV_max_safe_distance = 10
        self.CPU_chip_params = [10 ** -28, 3]
        self.discount_factor_bargain = 0.99
        self.veh_weight = 0.8 + 0.19 * random.random()
        self.mec_weight = 0.1 + 0.89 * random.random()
        self.uav_weight = 0.1 + 0.89 * random.random()
        self.all_Vehicles_num = 40
        self.all_MECs_num = 1
        self.all_UAVs_num = 4
        self.sum_strategy = 6
        self.MEC_hight = 10
        self.veh_velocity_min = 0
        self.veh_velocity_max = 1
        self.veh_direction_min = 0
        self.veh_direction_max = math.pi
        self.veh_memory_level_velocity = 0.6
        self.veh_memory_level_direction = 0.9
        self.veh_mean_velocity = random.random()
        self.veh_mean_direction = random.random() * math.pi / 3
        self.veh_Gauss_variance_velocity = 2
        self.veh_Gauss_variance_direction = 2
        self.uav_velocity_min = 0
        self.uav_velocity_max = 30
        self.UAV_altitude = 100
        self.uav_mean_velocity = 20
        self.profile_drag_coefficient = 0.012
        self.solidity = 0.05
        self.rotor_dis_area = 0.503
        self.blade_angular_velocity = 300
        self.rotor_radius = 0.4
        self.incremental_correction = 0.1
        self.tip_speed_rotor_blade = 120
        self.UAV_weight = 20
        self.mean_rotor_induced_power = 4.03
        self.air_density = 1.225
        self.uav_energy_par1 = 80
        self.uav_energy_par2 = 22
        self.uav_energy_par3 = 263.4
        self.uav_energy_par4 = 0.0092
        self.traj_utility_bound = 0.01
        self.traj_location_bound = 0.1
        self.carrier_frequency = 2 * (10 ** 9)
        self.noise_temperature = 300
        self.noise_figure = 6
        self.boltzman_constant = 1.38 * (10 ** -23)
        self.light_speed = 3 * (10 ** 8)
        self.noise_power = 10 ** (-98 / 10)
        self.path_loss_UE_LoS = 2.42
        self.path_loss_UE_NLoS = 4.28
        self.reference_distance = 100
        self.shadow_UE_LoS = 4
        self.shadow_UE_NLoS = 6
        self.nakagami_aver_gain = 1
        self.nakagami_UE_LoS = 4
        self.nakagami_UE_NLoS = 2
        self.fading_num = 1
        self.d1 = 18
        self.d2 = 36
        self.UAV_LoS_a = 10
        self.UAV_LoS_b = 0.6
        self.nakagami_UAV_LoS = 4
        self.nakagami_UAV_NLoS = 2
        self.addit_atten_UAV_NLoS = 0.2
        self.path_loss_UAV = 2
        self.min_task = 1
        self.task_slot = 0.1
        self.max_task = 5
        self.max_vehicle_num = 50
        self.min_vehicle_num = 10
        self.min_unit_price = 0.01 * (10 ** -9)
        self.max_unit_price = 1 * (10 ** -9)
        self.price_slot = 0.02 * (10 ** -9)
        self.min_resource = 1
        self.max_resource = 10
        self.resource_slot = 1
        self.min_queue = 1
        self.max_queue = 10
        self.queue_slot = 1
        self.min_trans = 1
        self.max_trans = 45
        self.trans_slot = 1
        self.min_time = 0.01
        self.min_dis = 0.1
        self.min_satisfacion_level = 0.05
        self.default_bargain_round = 5
